services:
  - type: web
    name: adn-eco
    env: dotnet
    repo: https://github.com/lylalarson2023-ux/mini-bank
    branch: master
    buildCommand: dotnet restore && dotnet publish -c Release -o out
    startCommand: dotnet out/MBANK_ETUDIANT.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ADMIN_API_USERNAME
        sync: false
      - key: ADMIN_API_PASSWORD
        sync: false
