// <auto-generated />
using System;
using MBANK_ETUDIANT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MBANK_ETUDIANT.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20260410104852_AddAdminAndPendingFlags")]
    partial class AddAdminAndPendingFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("MBANK_ETUDIANT.Models.SavingsPocket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CapitalActuel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CapitalInitial")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCible")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Objectif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatutGoal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SavingsPockets");
                });

            modelBuilder.Entity("MBANK_ETUDIANT.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Frais")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantBrut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoldeApres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MBANK_ETUDIANT.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DerniereMajInterets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Dette")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreTransactions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PendingPremiumUpgrade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Solde")
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
