// <auto-generated />
using System;
using ADN_pay.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADN_pay.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20260412142252_CreationInitiale")]
    partial class CreationInitiale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ADN_pay.Models.AdminLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cible")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatutResultat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("ADN_pay.Models.SavingsPocket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CapitalActuel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CapitalInitial")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCible")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Objectif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatutGoal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SavingsPockets");
                });

            modelBuilder.Entity("ADN_pay.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Frais")
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoldeApres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ADN_pay.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresseCasablanca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnneeEtude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CguAcceptees")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CvUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DerniereMajInterets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Dette")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocBourseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocDomicileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocIdentiteUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocPhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocProUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocScolariteUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Etablissement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filiere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LieuNaissance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatriculeEtudiant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationalite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NiveauEtude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreTransactions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassportOuCIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PendingCreditAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingCreditMotif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PendingCreditRequest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PendingPremiumUpgrade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReseauPrincipal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SituationMatrimoniale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Solde")
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatutEtudiant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
